# Generated by Django 2.2.2 on 2019-06-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('plot', models.TextField(max_length=360)),
                ('director', models.CharField(max_length=30)),
                ('length', models.CharField(max_length=10)),
                ('cast', models.CharField(max_length=50)),
                ('released_year', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='basic_app.Movie')),
            ],
        ),
    ]
