# Generated by Django 2.2.2 on 2019-06-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
