# Generated by Django 2.2.2 on 2019-06-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
