# Generated by Django 2.2.2 on 2019-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20190626_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='covers',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
