# Generated by Django 2.2.2 on 2019-06-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_movie_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='covers',
            field=models.URLField(default=''),
        ),
    ]
